### ISSUE TITLE
value labels dissapear when graph is panned

### ISSUE THREAD

**Issue by evanrich** [winne27/flot-valuelabels#10]
I've been using this for a while now, with great success, but recently I added in the navigation plugin to flot to allow panning of a graph (for historical reference in a graph), and noticed the value labels disappear when the graph is panned.  Perhaps this is a bug with the panning plugin and not yours, but I'm wondering if there is a way to redraw the labels?

Before
![graph1](https://cloud.githubusercontent.com/assets/518320/19319880/cbc69538-9063-11e6-9742-7c91c39f8633.PNG)

After click/pan:
![graph2](https://cloud.githubusercontent.com/assets/518320/19319885/d0fadf82-9063-11e6-9808-5287b4d3031a.PNG)

Thanks!

**Comment by winne27** [comment]
I will take a look at this problem if you deliver the following:

- a short description of the functionallity of plugin "panning" - never heard about it
- a Javascript program with data and code for testing this bug

**Comment by winne27** [comment]
I cannot reproduce this behaviour. In my example panning with labels worked fine.
Reopen this issue when you can deliver javascript code for testing.
