### ISSUE TITLE
Stacked graphs with not-all-series rendering valuelabels is broken

### ISSUE THREAD

**Issue by mintsoft** [winne27/flot-valuelabels#13]
Heya,

With a stacked bar graph if you have only some of the series rendering valueLabels the plugin places the value labels in the incorrect place for the series that are stacked ontop. 

There's an example of the problem here: https://github.com/mintsoft/flot-valuelabels/blob/bug-example/example4.html at the moment the label for France is rendered in the wrong place. If you switch `valueLabels` to true, then they're rendered in the correct place.

Thanks,
Rob

**Comment by winne27** [comment]
Pull request merged
