### ISSUE TITLE
Stacked Horizontal Bars Label Dislpay

### ISSUE THREAD

**Issue by jcusma** [winne27/flot-valuelabels#17]
Hello I am trying to display the value for each stacked segment of a horizontal bar chart. However the output look like this:

![image](https://user-images.githubusercontent.com/64594416/80715266-1c39e200-8ac4-11ea-98b9-c74c12ab3aa8.png)

This is how I have setup the options for the plot:

        var modelBardata = [{ label: "Accept Tests", data: modelAccepts, color: "#009900", valueLabels: { show: true, horizAlign: "insideCenter" }  },
            { label: "Reject Tests", data: modelRejects, color: "#CC0000", valueLabels: { show: true, horizAlign: "insideMax" }  }];

        $.plot($('#ctTestStatusByModel'), modelBardata, {
            series: {
                stack: true,
                bars: {
                    show: true
                }
            },
            bars: {
                barWidth: 0.7,
                horizontal: true,
                align: "center"
            },
            legend: {
                show: false
            },
            yaxis: {
                axisLabel: "Models",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: "Verdana Arial",
                axisLabelPadding: 10,
                ticks: modelTicks
            },
            xaxis: {
                axisLabel: "Count",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: 'Verdana, Arial',
                axisLabelPadding: 10
            }
        });
Do I have the wrong options set or is there something else I need to configure?

**Comment by winne27** [comment]
Hi, 

have a look on Githup.com/ winne27/flot-valuelabels to the documentation Wiki and try all the possible options for the paramter 
horizAlign 



Von: "jcusma" <notifications@github.com> 
An: "winne27/flot-valuelabels" <flot-valuelabels@noreply.github.com> 
CC: "Subscribed" <subscribed@noreply.github.com> 
Gesendet: Donnerstag, 30. April 2020 15:25:02 
Betreff: [winne27/flot-valuelabels] Stacked Horizontal Bars Label Dislpay (#17) 





Hello I am trying to display the value for each stacked segment of a horizontal bar chart. However the output look like this: 

[ https://user-images.githubusercontent.com/64594416/80715266-1c39e200-8ac4-11ea-98b9-c74c12ab3aa8.png ] 


This is how I have setup the options for the plot: 
var modelBardata = [{ label: "Accept Tests", data: modelAccepts, color: "#009900", valueLabels: { show: true, horizAlign: "insideCenter" }  },
        { label: "Reject Tests", data: modelRejects, color: "#CC0000", valueLabels: { show: true, horizAlign: "insideMax" }  }];

    $.plot($('#ctTestStatusByModel'), modelBardata, {
        series: {
            stack: true,
            bars: {
                show: true
            }
        },
        bars: {
            barWidth: 0.7,
            horizontal: true,
            align: "center"
        },
        legend: {
            show: false
        },
        yaxis: {
            axisLabel: "Models",
            axisLabelUseCanvas: true,
            axisLabelFontSizePixels: 12,
            axisLabelFontFamily: "Verdana Arial",
            axisLabelPadding: 10,
            ticks: modelTicks
        },
        xaxis: {
            axisLabel: "Count",
            axisLabelUseCanvas: true,
            axisLabelFontSizePixels: 12,
            axisLabelFontFamily: 'Verdana, Arial',
            axisLabelPadding: 10
        }
    }); 


Do I have the wrong options set or is there something else I need to configure?

**Comment by jcusma** [comment]
So I attempted each combination of horizAlign parameter setting and nothing change with the graph. My expectation of the number 2 being either in the center or near the right hand edge of the red portion of the stacked bar wasn't possible. The labels are behaving as expected for vertically stacked bars:

![image](https://user-images.githubusercontent.com/64594416/80833926-a2861f00-8bbd-11ea-939b-78d0eb2f26a5.png)

but for horizontal stacked bars this is what I get:

![image](https://user-images.githubusercontent.com/64594416/80833973-bd589380-8bbd-11ea-8466-9a1aaf2df802.png)

Could the 'X' of the label be calculated incorrectly when the graph is horizontal with stacked series?

**Comment by winne27** [comment]
Please send me your complete program including the data ( modelAccepts, modelRejects ) and the html frame. 


Von: "jcusma" <notifications@github.com> 
An: "winne27/flot-valuelabels" <flot-valuelabels@noreply.github.com> 
CC: "Werner Schäffer" <werner@schaeffer.net>, "Comment" <comment@noreply.github.com> 
Gesendet: Freitag, 1. Mai 2020 21:10:43 
Betreff: Re: [winne27/flot-valuelabels] Stacked Horizontal Bars Label Dislpay (#17) 





So I attempted each combination of horizAlign parameter setting and nothing change with the graph. My expectation of the number 2 being either in the center or near the right hand edge of the red portion of the stacked bar wasn't possible. The labels are behaving as expected for vertically stacked bars: 

[ https://user-images.githubusercontent.com/64594416/80833926-a2861f00-8bbd-11ea-939b-78d0eb2f26a5.png ] 


but for horizontal stacked bars this is what I get: 

[ https://user-images.githubusercontent.com/64594416/80833973-bd589380-8bbd-11ea-8466-9a1aaf2df802.png ] 


Could the 'X' of the label be calculated incorrectly when the graph is horizontal with stacked series?

**Comment by jcusma** [comment]
[WmaPortal.zip](https://github.com/winne27/flot-valuelabels/files/4567866/WmaPortal.zip)

So here's the zip file of the project. I populate the data arrays using an ajax call to return data from a database. The data in the modelAccepts and modelRejects is of this format {[2,0], [0,1],[6,2]} where the pairs are [value,index] So instead of using the ajax call you can just create the local JSON data package.

Thanks for the assistance.

**Comment by winne27** [comment]
It is a bug! For stacked bars only vertical orientation is supported. 
I have a quick fix for you
[jquery.flot.valuelabels.js.zip](https://github.com/winne27/flot-valuelabels/files/4568241/jquery.flot.valuelabels.js.zip)

Still the option "horizAlign: insideCenter" works only for the first stack, so use insideMax instead. 

An offical fix will follow soon, but first some testing is needed.

**Comment by jcusma** [comment]
Thank you for the quick update, your changes are working nicely. This is a good extension to the flot library.

**Comment by winne27** [comment]
In Version 2.3. the issue with stacked horizonzal bars is fixed
