### ISSUE TITLE
Suggestion:colorfull bar

### ISSUE THREAD

**Issue by lh2587451** [winne27/flot-valuelabels#6]
bars become more colorfull while callback function fillStyleCallback have been modified.in my case,data 's structure was added two params like [ ["January", 50,"#00ff00","#456"], ["February", 35,"#428bca","#456"].....], "#00ff00" stands for fill color and "#456" for border color. so callback function fillStyleCallback return the color i wanted.
code:
![image](https://cloud.githubusercontent.com/assets/8995146/14454593/f69d9c64-00cd-11e6-92a7-9dd2598dbe15.png)

result：
![image](https://cloud.githubusercontent.com/assets/8995146/14454626/0dbd4606-00ce-11e6-822e-1b968255f0e7.png)

there must be another better solution.please update.

**Comment by winne27** [comment]
This is the wrong place for this issue, because the fill color is not part of flot-valuelabels. 
I don't know the right place for this issue - you have to search for it.
